params shortname

set the duplicatePropertyKeyMode to error
set the strictProperties to true

set systems to {
	
	### LOCAL
	local_win10pro: {
		serverID: "192.168.216.7",
		portNum: 5900,
		password: "3ggpl4nt",
		type: "VNC"
	},

}

return systems.(shortname)


# Establishes connection to saved SUT via shortname.
-- Example: savedSUTs.connectTo(local_win10pro)
on connectTo systemShortname
	put savedSUTs(systemShortname) into targetSystem
	connect targetSystem
end connectTo