// The aim of this test is to ensure suite alignment with the target SUT for the purpose of EAI executions.
-- Prerequisite: connected to a standardized Windows 10 instance

# Close any open instance(s) and launch a fresh program.
calculator.closeProgram
calculator.launchProgram

# Ensures calculator clear button works properly while resetting program to known initial state.
calculator.pressClearButton
assert that calculator.displayedValue() equals zero

# Validate button states and background colors by looping through each element.
calculator.checkOperators
calculator.checkNumpad

# Demonstrates ability to validate on-screen results with expected calculated results.
assert that calculator.dividedBy(60, 1.5) equals 40
assert that calculator.dividedBy(8, 8) equals 1
assert that calculator.dividedBy(306, 6) equals 51

calculator.closeProgram