// The aim of this test is to ensure suite alignment with the target SUT for the purpose of EAI executions.
-- Prerequisite: connected to a standardized Windows 10 instance

# Close any open instance(s) and launch a fresh program.
calculator.closeProgram
calculator.launchProgram

# Ensures calculator clear button works properly while resetting program to known initial state.
calculator.pressClearButton
assert that calculator.displayedValue() equals zero

# Validate button states and background colors by looping through each element.
calculator.checkOperators
calculator.checkNumpad

# Demonstrates ability to validate on-screen results with expected calculated results.
assert that calculator.subtractedFrom(8, 3) equals -5
assert that calculator.subtractedFrom(72, 169) equals 97
assert that calculator.subtractedFrom(14, 14) equals 0

calculator.closeProgram