(* The aim of this test is to ensure suite alignment with the target SUT for the purpose of EAI executions.

-- Prerequisite: connected to a standardized disk image

*)

put <<applications/calculator>> into calculator

// Close any open instance(s) and launch a fresh program.
(calculator).closeProgram
(calculator).launchProgram

# Ensures calculator clear button works propertly while resetting program to known initial state.
(calculator).pressClearButton
assert that (calculator).displayedValue() equals zero

# Validate button states and background colors by looping through each element.
(calculator).checkOperators
(calculator).checkNumpad

# Demonstrates ability to validate on-screen results with expected calculated results.
assert that (calculator).addedTo(14, 2) equals 16
assert that (calculator).subtractedFrom(8, 3) equals -5
assert that (calculator).multipliedBy(4, 9) equals 36
assert that (calculator).dividedBy(60, 1.5) equals 40

(calculator).closeProgram